language: java

jdk:
  - oraclejdk8
  - openjdk7

script:
  - ./gradlew
  - ant test

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
